# Generated by Django 4.2 on 2023-05-02 18:02
# flake8: noqa

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Создан'), ('waiting for capture', 'Ожидание списания'), ('canceled', 'Отменен'), ('succeeded', 'Успешно завершен')], max_length=20, verbose_name='payment status'),
        ),
    ]
