# Generated by Django 4.2 on 2023-05-26 00:12
# flake8: noqa
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0005_alter_order_delivery_type_alter_orderitem_order'),
        ('paymentapp', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orderapp.order', verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Created by'), ('waiting for capture', 'Pending write-off'), ('canceled', 'Cancelled'), ('succeeded', 'Successfully completed')], max_length=20, verbose_name='payment status'),
        ),
    ]
