# Generated by Django 4.2 on 2023-05-26 00:15
# flake8: noqa
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0005_alter_order_delivery_type_alter_orderitem_order'),
        ('paymentapp', '0003_payment_order_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orderapp.order', verbose_name='order'),
        ),
    ]
