# Generated by Django 4.2 on 2023-04-26 07:59
# flake8: noqa
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0003_alter_product_options'),
        ('cartapp', '0002_alter_cart_is_active_alter_cartitem_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='productsapp.product', verbose_name='продукт'),
        ),
    ]
