# Generated by Django 4.2 on 2023-06-18 20:54
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0006_cartitem_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Discounted price'),
        ),
    ]
