# Generated by Django 4.2 on 2023-04-26 07:59
# flake8: noqa
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None,
                                                                 verbose_name='номер телефона'),
        ),
    ]
