# Generated by Django 4.2 on 2023-05-08 13:33
# flake8: noqa

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_image',
            field=models.ImageField(null=True, upload_to='profile_avatars/', verbose_name='аватар'),
        ),
    ]
