# Generated by Django 4.2 on 2023-05-15 11:23
# flake8: noqa
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_alter_profile_options_alter_profile_avatar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999, message="Phone number must be entered in the format '+71234567890'. 10 digits allowed."), django.core.validators.MinValueValidator(1000000000, message="Phone number must be entered in the format '+71234567890'. 10 digits allowed.")]),
        ),
    ]
