# Generated by Django 4.2 on 2023-05-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_alter_profile_phone_number'),
        ('profileapp', '0007_viewedproduct'),
    ]

    operations = [
    ]
