# Generated by Django 4.2 on 2023-05-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_merge_20230522_1447'),
        ('profileapp', '0008_merge_20230522_1454'),
    ]

    operations = [
    ]
