# Generated by Django 4.2 on 2023-05-12 18:31
# flake8: noqa
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0006_review_remove_product_is_delivered_and_more'),
        ('orderapp', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered', to='productsapp.product', verbose_name='product'),
        ),
    ]
