# Generated by Django 4.2 on 2023-05-25 23:20
# flake8: noqa
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0009_alter_cartdiscount_required_sum'),
        ('orderapp', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=0, max_length=100, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=0, max_length=50, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('default', 'Default delivery'), ('express', 'Express delivery')], default=1, max_length=20, verbose_name='delivery type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productsapp.seller', verbose_name='seller'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('not paid', 'Not paid for')], max_length=20, verbose_name='status'),
        ),
    ]
