# Generated by Django 4.2 on 2023-05-26 00:12
# flake8: noqa
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_order_address_order_city_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Default delivery', 'Default delivery'), ('Express delivery', 'Express delivery')], max_length=20, verbose_name='delivery type'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orderapp.order', verbose_name='order'),
        ),
    ]
