# Generated by Django 4.2 on 2023-05-31 16:32
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0005_alter_order_delivery_type_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Default delivery', 'Default delivery'), ('Express delivery', 'Express delivery')], default='Default delivery', max_length=20, verbose_name='delivery type'),
        ),
    ]
