# Generated by Django 4.2 on 2023-06-03 08:46
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0006_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('not paid', 'Not paid for')], default='not paid', max_length=20, verbose_name='status'),
        ),
    ]
