# Generated by Django 4.2 on 2023-06-17 16:09
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0008_order_fio_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='delivery price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='total discounted price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='total price'),
            preserve_default=False,
        ),
    ]
