# Generated by Django 4.2 on 2023-06-19 22:26
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0009_order_delivery_price_order_total_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='discounted price'),
            preserve_default=False,
        ),
    ]
