# Generated by Django 4.2 on 2023-04-22 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(blank=True,
                                          max_length=100,
                                          verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(max_length=100,
                                          verbose_name='name')),
                ('description', models.TextField(blank=True,
                                                 verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2,
                                              default=0,
                                              max_digits=8,
                                              verbose_name='price')),
                ('image', models.ImageField(upload_to='products',
                                            verbose_name='image')),
                ('archived', models.BooleanField(default=False,
                                                 verbose_name='archived')),
                ('is_delivered', models.BooleanField(
                    default=False,
                    verbose_name='is_delivered')),
                ('tags', taggit.managers.TaggableManager(
                    help_text='A comma-separated list of tags.',
                    through='taggit.TaggedItem',
                    to='taggit.Tag',
                    verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('-price', 'name', 'archived', 'is_delivered'),
            },
        ),
        migrations.CreateModel(
            name='TypeSpecific',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('category', models.ManyToManyField(
                    related_name='type_spec',
                    to='productsapp.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specific',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('description', models.TextField(blank=True,
                                                 null=True,
                                                 verbose_name='description')),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='specific',
                    to='productsapp.product')),
                ('type_spec', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='specific',
                    to='productsapp.typespecific')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(blank=True,
                                          max_length=100,
                                          verbose_name='name')),
                ('start_date', models.DateTimeField(blank=True)),
                ('expiration_date', models.DateTimeField(blank=True,
                                                         null=True)),
                ('description', models.TextField(blank=True,
                                                 null=True,
                                                 verbose_name='description')),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='discounted_products',
                    to='productsapp.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True)),
                ('updated_at', models.DateTimeField(
                    auto_now=True)),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(blank=True,
                                          max_length=100,
                                          verbose_name='name')),
                ('text', models.TextField(blank=True,
                                          verbose_name='text')),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments',
                    to='productsapp.product')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
    ]
