# Generated by Django 4.2 on 2023-04-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp',
         '0002_alter_category_is_active_alter_comment_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product',
                     'verbose_name_plural': 'products'},
        ),
    ]
