# Generated by Django 4.2 on 2023-04-28 16:13
# flake8: noqa
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_price_seller_selleritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='value')),
            ],
            options={
                'verbose_name': 'price slice',
                'verbose_name_plural': 'price slices',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='selleritem',
            name='price',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='sliceprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='productsapp.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='sliceprice',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slice_price', to='productsapp.seller', verbose_name='seller'),
        ),
    ]
