# Generated by Django 4.2 on 2023-05-04 11:07
# flake8: noqa

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_profile_phone_number'),
        ('productsapp', '0005_alter_product_image_alter_review_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='profileapp.profile'),
        ),
    ]
