# Generated by Django 4.2 on 2023-05-11 14:52

from django.db import migrations, models
import django.db.models.deletion

# flake8: noqa


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_alter_profile_options_alter_profile_avatar_image_and_more'),
        ('productsapp', '0006_review_remove_product_is_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='productsapp.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profileapp.profile'),
        ),
    ]
