# Generated by Django 4.2 on 2023-05-22 21:23
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0007_alter_review_product_alter_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='value')),
                ('start_date', models.DateField(blank=True, verbose_name='start date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='expiration date')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('priority', models.PositiveSmallIntegerField(verbose_name='priority')),
                ('required_sum', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='required sum')),
                ('required_quantity', models.PositiveSmallIntegerField(blank=True, verbose_name='required quantity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SetDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='value')),
                ('start_date', models.DateField(blank=True, verbose_name='start date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='expiration date')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('priority', models.PositiveSmallIntegerField(verbose_name='priority')),
                ('products', models.ManyToManyField(related_name='set_discounts', to='productsapp.product', verbose_name='products')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='value')),
                ('start_date', models.DateField(blank=True, verbose_name='start date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='expiration date')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('priority', models.PositiveSmallIntegerField(verbose_name='priority')),
                ('categories', models.ManyToManyField(related_name='category_discounts', to='productsapp.category')),
                ('products', models.ManyToManyField(related_name='product_discounts', to='productsapp.product', verbose_name='products')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
