# Generated by Django 4.2 on 2023-05-25 23:20
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0008_cartdiscount_setdiscount_productdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdiscount',
            name='required_sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='required sum'),
            preserve_default=False,
        ),
    ]
