# Generated by Django 4.2 on 2023-06-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0010_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='short_description'),
        ),
    ]
