# Generated by Django 4.2 on 2023-06-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0011_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_limited',
            field=models.BooleanField(default=False, verbose_name='limited'),
        ),
    ]
