# Generated by Django 4.2 on 2023-06-05 18:33
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0012_product_is_limited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartdiscount',
            options={'verbose_name': 'Cart Discount', 'verbose_name_plural': 'Cart Discounts'},
        ),
        migrations.AlterModelOptions(
            name='productdiscount',
            options={'verbose_name': 'Product Discount', 'verbose_name_plural': 'Product Discounts'},
        ),
        migrations.AlterModelOptions(
            name='setdiscount',
            options={'verbose_name': 'Set Discount', 'verbose_name_plural': 'Set Discounts'},
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='categories',
            field=models.ManyToManyField(related_name='category_discounts', to='productsapp.category', verbose_name='categories'),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
