# Generated by Django 4.2 on 2023-06-05 19:26
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0013_category_icon_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='categories_icons/', verbose_name='icon (SVG)'),
        ),
    ]
