# Generated by Django 4.2 on 2023-06-05 20:14
# flake8: noqa
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0014_alter_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
