# Generated by Django 4.2 on 2023-06-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0013_alter_cartdiscount_options_and_more'),
        ('productsapp', '0015_remove_category_image'),
    ]

    operations = [
    ]
