# Generated by Django 4.2 on 2023-06-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0016_merge_20230606_1333'),
        ('productsapp', '0016_merge_20230607_1954'),
    ]

    operations = [
    ]
