# Generated by Django 4.2 on 2023-06-10 12:05
# flake8: noqa
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0017_merge_20230608_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdiscount',
            name='priority',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='cartdiscount',
            name='required_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='required quantity'),
        ),
        migrations.AlterField(
            model_name='cartdiscount',
            name='required_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='required sum'),
        ),
        migrations.AlterField(
            model_name='cartdiscount',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, related_name='category_discounts', to='productsapp.category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='priority',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='products',
            field=models.ManyToManyField(blank=True, default=None, related_name='product_discounts', to='productsapp.product', verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='setdiscount',
            name='priority',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='setdiscount',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='value'),
        ),
    ]
