# Generated by Django 4.2 on 2023-06-27 09:56
# flake8: noqa
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productsapp', '0019_merge_20230610_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
